//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checklist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reasons
    {
        public int IdReason { get; set; }
        public int IdTask { get; set; }
        public int IdStep { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string Description { get; set; }
    
        public virtual tasks tasks { get; set; }
        public virtual step step { get; set; }
    }
}
